#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#  Configuration file for "Backup". #
#  @author Domenic Horner (gamerx)  #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

#======== Backup Settings ==========#

## How often show the backup run? (Default: "15M" / 15 Minutes)
# (Note: -1 Will disable automatic backups.)
# Format: [Time][M-Minutes, H-Hours, D-Days, W-Weeks]
backupinterval: 15M

## Enable scheduled save-all? (Default: "-1" / Off)
# (Note: -1 disables this feature.)
# Format: [Time][M-Minutes, H-Hours, D-Days, W-Weeks]
saveallinterval: -1

## How many backups are retained? (Default: 25)
# If this limit is hit, the oldest backup(s) will be removed. 
maxbackups: 25

## Should backups be performed on an empty server? (Default: false)
# When the last player leaves the server, a final backup will be made. The automatic backup cycle will resume when a player re-joins.
backupemptyserver: false

## Should we backup the entire folder? (Default: false)
# Use with caution, as this will be a long, large backup, it automatically ignores the backup folder, so it can still be in the server folder.
# Using this will ignore "backupworlds", "backupplugins", "skipworlds", "skipplugins", and "splitbackup"
backupeverything: false

## If permissions system is not available, should everyone be able to access all commands, or just ops? (Default: true)
# If set to false, all players will be able to perform all commands, unless you use a permissions system.
onlyops: true

## Enables the auto-save function after the backup. (Defualt: true)
# Note: If you set this to false, this plugin will backup your worlds but not save the data from the memory to your hard disc. If the server crashes between
# backups, all work is lost. Disable if you use another plugin to save the world to disk (EG: autosave).
enableautosave: true

## Option to always perform a /save-all on backup. (Default: false)
# If false, /save-all's are only performed when a backup is required.
alwayssaveall: false


#======== File & Location Settings ==========#

## Directory to store backup in. (Default: backups)
# Note: Path can be relative, or absolute.
backuppath: backups

## Do we use the temp folder when doing backup? (Default: true)
# It is required for Ziped backups.
usetemp: true

## Name for the temp folder. (Default: temp)
# This stores tempoary files while backup is in progress.
tempfoldername: temp

## Whether to ZIP Backups or not. (Default: true)
# If enabled, backups will be compressed and stored in a ZIP archive named with the current timestamp.
# If disabled, the backup will stored in a folder with the timestamp.
zipbackup: true

## Should all the worlds be split into their own files? (Default: false)
# Needs to be true to be compatible with WorldEdit.
splitbackup: false

## Custom date format string that is appended to every backup.
## If left empty, the default date format is used.
## This has to be a Java String.format string, see
## http://download.oracle.com/javase/1.5.0/docs/api/java/util/Formatter.html#syntax
##for reference.
## Example: -%1$tY%1$tm%1$td-%1$tH%1$tM%1$tS (YYYYMMDD-HHMMSS: 20101201-011323) (conforms to ISO 8601)
dateformat: '%1$tY%1$tm%1$td-%1$tH%1$tM%1$tS'


#======== Content Settings ==========#

## What to backup. (Default: true, true)
# Will give warning if either is disabled.
backupworlds: true
backupplugins: true

## Worlds for the backup to skip. (Default: none)
# Seperate by a semicolon. eg. World1;World2;Nether
skipworlds:

## List of files to exclude from the plugin backup. (Default: none)
# Seperate by a semicolon. eg. Plugin1;Plugin2;Plugin3. This takes effect at all directory levels.
skipplugins:


#======== Notification & Logging Settings ==========#

## Should we display messages in server/console log? (Default: true)
# If false messages will only be logged to file.
displaylog: true

## Should we log the plugins logs to the file. (Default: false)
# File is specified in "backuplogname".
logtofile: false

## Backup log file name. (Default: backup.log)
# Filename for log file, it is stored under the plugins data folder.
backuplogname: backup.log

## Should we send messages in-game on backup complete. (Default: true)
# False will only notify players with the "backup.notify" permission.
notifyallplayers: true

## Prints a list of configuration on plugin enable. (Default: true)
# This is usefull for debugging configuration.
showconfigonstartup: true

## Enable online version checking? (Default: true)
# Requires internet connectivity.
enableversioncheck: true

###############################################
##   Internal Settings (Read: DO NOT EDIT)   ##
###############################################

requiredstrings: str-29
version: 1.8.7-dev