name: Backup
version: 1.8-dev
description: Backup plugin for Bukkit API.
authors: [Meldanor, gamerx, lycano]
main: net.tgxn.bukkit.backup.PluginMain
commands:
  backup:
    description: Starts a backup of the server
    usage: "Usage: /<command> [Args]"