name: Backup
version: 1.8
description: CraftBukkit server Backup plugin.
authors: [Meldanor, gamerx]
main: backup.Main
commands:
  backup:
    description: Starts a backup of the server
    usage: "Usage: /<command> [Args]"